
remote_theme : mmistakes/minimal-mistakes

title:              Soon Blog
email:              dirmtk@gmail.com
description:        Soon Soon
author:             Soon
baseurl:            ""
url:                "https://Soon.github.io"


# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
